# Generated by Django 4.2.6 on 2023-11-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productosolicitado",
            old_name="producto",
            new_name="id_producto",
        ),
        migrations.RenameField(
            model_name="productosolicitado",
            old_name="solicitud",
            new_name="id_solicitud",
        ),
    ]
