# Generated by Django 4.2.6 on 2023-11-21 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_solicitud_nota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productosolicitado",
            name="id_solicitud",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos_solicitados",
                to="core.solicitud",
            ),
        ),
    ]
