# Generated by Django 4.2.6 on 2023-10-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_is_superuser_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rol",
            field=models.CharField(max_length=15),
        ),
    ]
