# Generated by Django 4.2.6 on 2023-11-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_producto_productosolicitado_id_producto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productosolicitado",
            old_name="solicitud",
            new_name="id_solicitud",
        ),
    ]
