# Generated by Django 4.2.6 on 2023-11-21 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_productosolicitado_id_solicitud"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productosolicitado",
            name="id_solicitud",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.solicitud"
            ),
        ),
    ]
