# Generated by Django 4.2.6 on 2023-11-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_productosolicitado_id_solicitud"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                default="path/to/default/photo.jpg", upload_to="user_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="estado",
            field=models.CharField(default="En Revisión", max_length=20),
        ),
    ]
