# Generated by Django 4.2.6 on 2024-01-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_photo_alter_solicitud_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
