# Generated by Django 4.2.6 on 2023-10-29 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitud",
            name="profesor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_profesor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="solicitudes",
            field=models.ManyToManyField(
                blank=True, related_name="usuarios_solicitudes", to="core.solicitud"
            ),
        ),
    ]
