# Generated by Django 4.2.6 on 2023-11-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_user_rol_alter_user_rut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="carrera",
            field=models.ManyToManyField(null=True, to="core.carrera"),
        ),
        migrations.AlterField(
            model_name="user",
            name="curso",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
