# Generated by Django 4.2.6 on 2023-11-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_user_carrera_alter_user_curso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="carrera",
            field=models.ManyToManyField(blank=True, to="core.carrera"),
        ),
    ]
