# Generated by Django 4.2.6 on 2023-11-11 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_user_carrera"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitud",
            name="aprobacion",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="solicitud",
            name="profesor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_profesor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
